### ISSUE TITLE
Feat: RedHat Support

### ISSUE THREAD

**Issue by deekayen** [while-true-do/ansible-role-sys_update#1]
Could you symlink the CentOS task file to RedHat.yml? This new version of the role isn't running on our RHEL 7 systems without that.

**Comment by dschier-wtd** [comment]
Hey, thanks for the issue.

I am currently working on a RedHat Support. Since RedHat supports some more detailed upgrades like security only/bugfixes/critical/etc. I think a little bit more effort is needed to properly support RedHat.

Give me this week and I will update the role with RedHat Support and would appreciate a review from your side.

**Comment by dschier-wtd** [comment]
See here: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-keeping_your_system_up-to-date

**Comment by dschier-wtd** [comment]
https://twitter.com/daniel_wtd/status/1123652869989781504?s=21

Trying to find a redhat container for testing.

**Comment by dschier-wtd** [comment]
Hey, I have released 1.1.0 with RedHat support and some other improvements.
For docker testing this is currently running on a centos. with the future lxc environment, we will see real redhat images for testing.

Would be awesome, if you can test it from your side and provide feedback.
